spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/capstone
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true #페이징 1부터 시작하도록 설정

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 업로드할 수 있는 파일의 최대 크기 설정
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}  # Gmail 계정
    password: ${MAIL_APP_PASSWORD}  # Gmail 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.apache.coyote.http11: trace
    org.springframework.web.multipart: debug

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 #토큰 만료 시간 : 1시간 설정


